<a href="https://colab.research.google.com/github/criemqui/calculadora/blob/main/Numpy_repaso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# calculos matematicos
# array -> arreglos
import numpy as np # np.
import pandas as pd # pd

arr = np.array([[1, 1, 1, 1, 1, 1],[1, 2, 3, 4, 5, 6],[1, 2, 3, 4, 5, 6],[6, 6, 6, 6, 6, 6]])
print(arr[-1])

print('AEIOU'[0])

[6 6 6 6 6 6]
A


In [ ]:
print('AEIOU'[0])

A


In [ ]:
x = np.arange(10000000)
x

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [ ]:
print(x ** 100)

[100 101 102 103]


In [ ]:
print("hola")

hola


In [ ]:
import numpy as np

calificaciones = np.array([
   [1, 60, 63, 63, 99, 69],
   [2, 79, 81, 96, 83, 66],
   [3, 84, 84, 72, 61, 98],
   [4, 99, 83, 84, 77, 97],
   [5, 85, 73, 68, 69, 80],
   [6, 76, 65, 75, 60, 78],
   [7, 95, 84, 89, 79, 79],
   [8, 74, 99, 92, 61, 69],
   [9, 92, 91, 70, 83, 95],
   [10, 71, 88, 94, 60, 60]
])

In [ ]:
print(calificaciones[3, 1:6])
print(np.mean(calificaciones[3, 1:6]))

[99 83 84 77 97]
88.0


In [ ]:
print(calificaciones[:,1:])

[[60 63 63 99 69]
 [79 81 96 83 66]
 [84 84 72 61 98]
 [99 83 84 77 97]
 [85 73 68 69 80]
 [76 65 75 60 78]
 [95 84 89 79 79]
 [74 99 92 61 69]
 [92 91 70 83 95]
 [71 88 94 60 60]]


In [ ]:
# promedio de materias
promedio_asignaturas= np.mean(calificaciones[:,1:], axis=0)
promedio_asignaturas

array([81.5, 81.1, 80.3, 73.2, 79.1])

In [ ]:
np.mean(calificaciones[:,1:])

79.04

In [ ]:
# calificacion promedio de estudiantes
cal_est_prom = np.mean(calificaciones[:,1:], axis=1)

In [ ]:
print(cal_est_prom)

[70.8 81.  79.8 88.  75.  70.8 85.2 79.  86.2 74.6]


In [ ]:
# ejercicio 3
np.min(cal_est_prom)

70.8

In [ ]:
np.max(cal_est_prom)

88.0

In [ ]:
np.argmax(cal_est_prom)

3

In [ ]:
np.argmin(cal_est_prom)

0

In [ ]:
calificaciones[3]

array([ 4, 99, 83, 84, 77, 97])

In [ ]:
#desviacion estandar
import math

[x, y, z]
prom = np.mean()

sumatoria = ((x-prom)**2) + ((y-prom)**2) + ((z-prom)**2)

# n : nro de elementos
desviacion = math.sqrt(sumatoria / (n-1))

NameError: name 'y' is not defined